export const UPDATE_CELL = 'UPDATE_CELL';
export const SET_INITIAL_GRID = 'SET_INITIAL_GRID';
export const GET_INITIAL_GRID = 'GET_INITIAL_GRID';
export const START_GAME = 'START_GAME';
export const SHOW_GROWING = 'SHOW_GROWING';
